# Generated by Django 4.0.4 on 2022-08-30 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covidsaverr2app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='covidappuser',
            old_name='ezbo',
            new_name='username',
        ),
    ]
