# Generated by Django 4.0.4 on 2022-09-01 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covidsaverr2app', '0002_rename_ezbo_covidappuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='covidappuser',
            name='podkategorija_skopje',
            field=models.CharField(choices=[('1', 'Joy'), ('1', 'Destan')], default='restaurant', max_length=20),
        ),
        migrations.CreateModel(
            name='Restoran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('grad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='covidsaverr2app.grad')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=50)),
                ('grad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='covidsaverr2app.grad')),
                ('restoran', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='covidsaverr2app.restoran')),
            ],
        ),
    ]
