# Generated by Django 4.0.4 on 2022-09-04 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covidsaverr2app', '0003_grad_alter_covidappuser_podkategorija_skopje_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='covidappuser',
            name='year_of_birth',
        ),
    ]
