# Generated by Django 4.0.4 on 2022-09-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidsaverr2app', '0005_appuser_remove_covidappuser_tel_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='grad',
            name='grad',
            field=models.CharField(choices=[('ohrid', 'OHRID'), ('struga', 'STRUGA'), ('skopje', 'SKOPJE'), ('tetovo', 'TETOVO'), ('prilep', 'PRILEP'), ('veles', 'VELES'), ('kavadarci', 'KAVADARCI'), ('negotino', 'NEGOTINO'), ('stip', 'STIP'), ('berovo', 'BEROVO'), ('debar', 'KICEVO'), ('bitola', 'BITOLA')], max_length=50, null=True),
        ),
    ]
